### ISSUE TITLE
Broken Links on "Compile the RISC-V Linux and the ramdisk root.bin"

### ISSUE THREAD

**Issue by DylanRichards** [lowRISC/lowrisc-web#63]
The page: https://www.lowrisc.org/docs/untether-v0.2/linux_compile/ has multiple broken links
- https://github.com/riscv/riscv-linux#linuxrisc-v is an archived project that can be removed
- https://www.lowrisc.org/www.busybox.net should be https://busybox.net/
- https://www.lowrisc.org/spike#spike-boot should be https://www.lowrisc.org/docs/untether-v0.2/spike/

**Comment by imphil** [comment]
Fixed in https://github.com/lowRISC/lowrisc-web/pull/64
